# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import solver_env_pb2 as solver__env__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in solver_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolverEnvStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/unitime.rl.SolverEnv/Reset',
                request_serializer=solver__env__pb2.InstanceId.SerializeToString,
                response_deserializer=solver__env__pb2.Observation.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/unitime.rl.SolverEnv/Step',
                request_serializer=solver__env__pb2.Action.SerializeToString,
                response_deserializer=solver__env__pb2.StepResult.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/unitime.rl.SolverEnv/Info',
                request_serializer=solver__env__pb2.Empty.SerializeToString,
                response_deserializer=solver__env__pb2.Metrics.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/unitime.rl.SolverEnv/Save',
                request_serializer=solver__env__pb2.SavePath.SerializeToString,
                response_deserializer=solver__env__pb2.Empty.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/unitime.rl.SolverEnv/Close',
                request_serializer=solver__env__pb2.Empty.SerializeToString,
                response_deserializer=solver__env__pb2.Empty.FromString,
                _registered_method=True)


class SolverEnvServicer:
    """Missing associated documentation comment in .proto file."""

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolverEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=solver__env__pb2.InstanceId.FromString,
                    response_serializer=solver__env__pb2.Observation.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=solver__env__pb2.Action.FromString,
                    response_serializer=solver__env__pb2.StepResult.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=solver__env__pb2.Empty.FromString,
                    response_serializer=solver__env__pb2.Metrics.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=solver__env__pb2.SavePath.FromString,
                    response_serializer=solver__env__pb2.Empty.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=solver__env__pb2.Empty.FromString,
                    response_serializer=solver__env__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unitime.rl.SolverEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unitime.rl.SolverEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolverEnv:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unitime.rl.SolverEnv/Reset',
            solver__env__pb2.InstanceId.SerializeToString,
            solver__env__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unitime.rl.SolverEnv/Step',
            solver__env__pb2.Action.SerializeToString,
            solver__env__pb2.StepResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unitime.rl.SolverEnv/Info',
            solver__env__pb2.Empty.SerializeToString,
            solver__env__pb2.Metrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unitime.rl.SolverEnv/Save',
            solver__env__pb2.SavePath.SerializeToString,
            solver__env__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unitime.rl.SolverEnv/Close',
            solver__env__pb2.Empty.SerializeToString,
            solver__env__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PolicyStub:
    """Remote policy used by GrpcPolicy (Java asks Python for an action).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Act = channel.unary_unary(
                '/unitime.rl.Policy/Act',
                request_serializer=solver__env__pb2.Observation.SerializeToString,
                response_deserializer=solver__env__pb2.Action.FromString,
                _registered_method=True)


class PolicyServicer:
    """Remote policy used by GrpcPolicy (Java asks Python for an action).
    """

    def Act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=solver__env__pb2.Observation.FromString,
                    response_serializer=solver__env__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unitime.rl.Policy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unitime.rl.Policy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Policy:
    """Remote policy used by GrpcPolicy (Java asks Python for an action).
    """

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unitime.rl.Policy/Act',
            solver__env__pb2.Observation.SerializeToString,
            solver__env__pb2.Action.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
