"""Generate a one-time SQL loader for UniTime instructional rooms.

UniTime's Buildings & Rooms data-exchange format imports *external* rooms.
Those records are useful for event integrations, but the course solver reads the
internal ``building``, ``room``, and ``room_dept`` tables.  This script bridges
that documented model gap for the local COEP pilot database.

The generated SQL is deliberately guarded: it refuses to run if the target
session already contains instructional rooms.  It uses a reserved high ID
range to avoid colliding with UniTime's Hibernate ID allocator.
"""

from __future__ import annotations

from pathlib import Path
from xml.etree import ElementTree as ET


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "unitime-out" / "buildingRoomImport.xml"
OUTPUT = ROOT / "unitime-out" / "load_instructional_rooms.sql"
ID_BASE = 9_000_000_000_000


def quote(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    root = ET.parse(INPUT).getroot()
    campus = root.attrib["campus"]
    term = root.attrib["term"]
    year = root.attrib["year"]
    next_id = ID_BASE
    building_ids: dict[str, int] = {}
    lines = [
        "-- Generated by scripts/gen_instructional_room_sql.py",
        "-- Required because Buildings & Rooms XML creates external rooms only.",
        "START TRANSACTION;",
        (
            "SET @coep_session := (SELECT uniqueid FROM sessions "
            f"WHERE academic_initiative={quote(campus)} AND academic_term={quote(term)} "
            f"AND academic_year={quote(year)});"
        ),
        "SET @coep_dept := (SELECT uniqueid FROM department WHERE session_id=@coep_session AND dept_code='0101');",
        "-- Abort safely on a wrong/missing session or a session that already has rooms.",
        "SELECT CASE WHEN @coep_session IS NULL THEN 1/0 WHEN @coep_dept IS NULL THEN 1/0 "
        "WHEN EXISTS (SELECT 1 FROM room WHERE session_id=@coep_session) THEN 1/0 ELSE 1 END AS preflight;",
    ]

    for building in root.findall("building"):
        building_id = next_id
        next_id += 1
        abbreviation = building.attrib["abbreviation"]
        building_ids[abbreviation] = building_id
        lines.append(
            "INSERT INTO building (uniqueid, session_id, abbreviation, name, coordinate_x, coordinate_y, external_uid) "
            f"VALUES ({building_id}, @coep_session, {quote(abbreviation)}, {quote(building.attrib['name'])}, "
            f"{quote(building.attrib.get('locationX'))}, {quote(building.attrib.get('locationY'))}, "
            f"{quote(building.attrib.get('externalId'))});"
        )
        for room in building.findall("room"):
            room_id = next_id
            room_dept_id = next_id + 1
            next_id += 2
            type_ref = room.attrib.get("scheduledRoomType", room.attrib.get("roomClassification", "genClassroom"))
            lines.append(
                "INSERT INTO room (uniqueid, external_uid, session_id, building_id, room_number, capacity, permanent_id, "
                "coordinate_x, coordinate_y, ignore_too_far, classification, display_name, exam_capacity, room_type) "
                f"VALUES ({room_id}, {quote(room.attrib.get('externalId'))}, @coep_session, {building_id}, "
                f"{quote(room.attrib['roomNumber'])}, {int(room.attrib.get('capacity', '0'))}, {room_id}, "
                f"{quote(room.attrib.get('locationX', building.attrib.get('locationX')))}, "
                f"{quote(room.attrib.get('locationY', building.attrib.get('locationY')))}, 0, "
                f"{quote(room.attrib.get('roomClassification'))}, {quote(room.attrib.get('displayName'))}, 0, "
                f"(SELECT uniqueid FROM room_type WHERE reference={quote(type_ref)}));"
            )
            lines.append(
                "INSERT INTO room_dept (uniqueid, room_id, department_id, is_control) "
                f"VALUES ({room_dept_id}, {room_id}, @coep_dept, 1);"
            )

    lines.extend(["COMMIT;", "SELECT COUNT(*) AS instructional_rooms_created FROM room WHERE session_id=@coep_session;"])
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
